config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :articles,  path: 'blog'
  end

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :galeris,  path: 'galeri'
  end

  get 'iletisim', to: 'iletisim#index'

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :duyurulars,  path: 'duyurular'
  end

  scope(path_names: {new: 'yeni', edit: 'değiştermek'}) do
    resources :yonetims,  path: 'yönetim'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_favicon.html.erb
<% %w(57 60 72 76 114 120 144 152).each do |size| %>
  <%= favicon_link_tag "fav/apple-touch-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

app/views/layouts/_footer.html.erb
<!--Footer-->
<br>
<div id="footer3" class="container-fluid">
  <br>
  <div id="footer4" class="container">
    <div class="row">
      <div class="col-6 col-md-3">
        <a href='http://www.fatsa.gov.tr/' target="_blank" , alt="fatsagov">
          <%= image_tag("icon/1.png", size: "100") %>
        </a>
      </div>

      <div class="col-6 col-md-3">
        <a href='http://www.fatsa.bel.tr/' target="_blank" , alt="fatsagov">
          <%= image_tag("icon/2.png", size: "100") %>
        </a>
      </div>

      <div class="col-6 col-md-3">
        <a href='http://www.ordu.bel.tr/' target="_blank" , alt="fatsagov">
          <%= image_tag("icon/3.png", size: "100") %>
        </a>
      </div>

      <div class="col-6 col-md-3">
        <a href='http://www.ordu.gov.tr/' target="_blank" , alt="fatsagov">
          <%= image_tag("icon/4.png", size: "100") %>
        </a>
      </div>
    </div>
  </div>
  <br>
  <br>
</div>

<div id="footer" class="container-fluid">
  <div id="footer2" class="container">
    <div class="row">
      <div class="col-sm-6 col-md-6">
        <p>
          <a href="tel:+905384715252" id="telefon" class="sog"><i class="fas fa-phone" aria-hidden="true"></i><%= t('footer.phone') %>
          </a></p>

        <p>
          <a href="mailto:aslancami@aslancamikoyudernegi.com.tr" id="email"><i class="fas fa-envelope" aria-hidden="true"></i><%= t('footer.email') %>
          </a></p>

        <p><i class="fas fa-map-marker-alt" aria-hidden="true"></i><%= t('footer.address') %></p>
        <br>
      </div>

      <div id="p" class="col-sm-6 col-md-6">
        <a href='https://www.facebook.com/groups/961187180582440/?fref=nf' target="_blank" , alt="f">
          <%= image_tag("soz/f.png") %>
        </a>
        <a href='https://www.twitter.com' target="_blank" , alt="t">
          <%= image_tag("soz/t.png") %>
        </a>
        <a href='https://www.youtube.com' target="_blank" , alt="u">
          <%= image_tag("soz/u.png") %>
        </a>
      </div>
    </div>
  </div>
</div>

<div id="avtor" class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <p><a href="mailto:ovin999@gmail.com"><%= t('footer.made_by') %></a></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_logo.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <%= link_to(image_tag("logo150.png", class: "img-fluid d-block mx-auto", alt: "Responsive image", id: "logo"), root_path) %>
    </div>

    <div class="col-sm-10">
      <h1><%= t :h1 %></h1>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<!--Navbar-->
<nav class="navbar navbar-expand-sm">
  <div class="container">
    <ul class="nav nav-pills">
      <li class="nav-link"><%= link_to "", root_path, class: "fas fa-home", id: "icon" %></li>

      <li class="nav-link"><%= link_to t(:'navigation.insanlar'), yonetims_path %></li>
      <li class="nav-link"><%= link_to t(:'navigation.galeri'), galeris_path %></li>
      <li class="nav-link"><%= link_to t(:'navigation.iletisim'), iletisim_path %></li>
      <li class="nav-link"><%= link_to t(:'navigation.duyurular'), duyurulars_path %></li>
      <li class="nav-link"><%= link_to t(:'navigation.blog'), articles_path %></li>
    </ul>

    <ul class="navbar-nav ml-auto">
      <li class=" nav-item nav-link"><%= link_to t(:'navigation.uye_ol'), new_user_registration_path, class: "fas fa-user" %></li>
      <li class="nav-link">
        <% if user_signed_in? %>
          <%= link_to t(:'navigation.cikis'), destroy_user_session_path, method: :delete, id: "cikis" %>
          <p id="curuser"><%= current_user.email %></p>
        <% else %>
          <%= link_to t(:'navigation.giris_yap'), new_user_session_path, class: "fas fa-sign-in-alt" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">

  <!-- Wrapper for slides -->
  <div class="container-fluid">
    <div class="row">
      <div id="slider" class="col-sm-12">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag("slider/1111.jpg", alt: "", style: "width:100%") %>
          </div>

          <div class="carousel-item">
            <%= image_tag("slider/2222.jpg", alt: "", style: "width:100%") %>
          </div>

          <div class="carousel-item">
            <%= image_tag("slider/3333.jpg", alt: "", style: "width:100%") %>
          </div>

          <div class="carousel-item">
            <%= image_tag("slider/4444.jpg", alt: "", style: "width:100%") %>
          </div>

          <div class="carousel-item">
            <%= image_tag("slider/5555.jpg", alt: "", style: "width:100%") %>
          </div>

          <!-- Left and right controls -->
          <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </a>
          <a class="carousel-control-next" href="#myCarousel" data-slide="next">
            <span class="carousel-control-next-icon"></span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<!--Slider end-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="tr">
  <head>
    <title><%= yield(:title) %> | Aslancamikoyudernegi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

<!--    Slider-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!--    Slider end-->

    <%= favicon_link_tag 'fav/fav.ico' %>
    <%= favicon_link_tag 'fav/fav.ico', rel: 'apple-touch-icon', type: 'image/png' %>

    <%= render 'layouts/favicon' %>

  </head>

  <body>
  <%= render 'layouts/navigation' %>


  <%= render 'layouts/logo' %>


  <%= yield %>

  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/welcome/index.html.erb
<%= render 'layouts/slider' %>

<div class="container">
  <div class="row">
    <div id="baskan" class="col-sm-4">
      <div class="thumbnail">
        <%= image_tag("boss.jpg", class: "img-fluid rounded", alt: "baskan", id: "boss") %>

        <div id="name" class="caption">
          <%= t('boss') %> <br> <%= t('boss_name') %>
        </div>
      </div>
    </div>

    <div id="merhaba" class="col-sm-8">
      <p><%= t('merhaba') %></p>
      <p><%= t('merhaba_text') %></p>
      <p><%= t('byebye') %></p>
    </div>
  </div>
</div>